### ISSUE TITLE
Add check for unloaded data today to sup-summerize

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#28]
Desired behavior:
console output of :
1. "All rats have data entered today"
2. "Data not entered for x rats: <list of rats>"

Code for getting list of runs not entered.
> # Not loaded today --------------------------------------------------------
>rat_archive %>% filter(is.na(end_date)) %>%
> filter(! Rat_name %in% c(run_archive %>% filter(date == str_remove_all(Sys.Date(), "-")) %>% .$rat_name %>% as.list)) %>%
>  .$Rat_name

**Comment by tofof** [comment]
Dupes #27 and 4th bullet of #26
