### ISSUE TITLE
Warning: unknown column FA

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#31]
See example file in the Z:\Issues folder
9/26/22 LP3

This is the only time I have seen that warning. I spent no time trying to figure it out. I don't think it prevented the analysis from continuing, but the file still errors out due to #30

**Comment by nohelix** [comment]
Loading file...	
C:/Users/Noelle/Box/Behavior Lab/Projects (Behavior)/Tsc2 Eker/data/20221118/GP5_8kHz_60-90dB_50ms_4s_20221118-111551_BOX#005.mat
[1] "C:/Users/Noelle/Box/Behavior Lab/Projects (Behavior)/Tsc2 Eker/data/20221118/GP5_8kHz_60-90dB_50ms_4s_20221118-111551_BOX#005.mat"
Stim file:	8kHz_60-90dB_50ms_4s
	Trials: 401	Hit%: 74.7	FA%: 0.8
Analysis type:	Tone (Single)
Warning: Unknown or uninitialised column: `FA`.
Calculated run statistics.
Filename checks complete.
Warning in Check_Performance_Cutoffs() : Low hit rate: 74.7%

Archiving Run... Trials... 
Run 20221118111551_111.739003658295_3.39539600387812 of GP5 (#161) successfully added to archives (in environment and on disk).

**Comment by nohelix** [comment]
Caused by no FAs outside of the 1st block

**Comment by nohelix** [comment]
Already had a check to create the column:
`      if(!("FA" %in% colnames(df))) {
        df = df %>% add_column(FA = NA)
        FAnum = 0
      }`

So only need to suppress the warning.

**Comment by tofof** [comment]
Suppress.
Try-catch is for errors, not warnings.
