### ISSUE TITLE
Shiny Interface

### ISSUE THREAD

**Issue by tofof** [Auerbach-Lab/Behavior-autoanalysis#33]
Use the Shiny framework to create the main interface for undergraduates to use for data entry.

- [x] Refactor main to reduce reliance on globals
- [x] Validate inputs and input agreement prior to doing expensive import process.
- [x] Display graphs and offer space for annotation
  - [x] Weight Graph
  - [x] Secondary Graph
    - [x] Rxn Graph
    - [x] Ben wanted .. some other option
    - [x] Other alternative for when Rxn vs dB doesn't make sense due to only 1 intensity
- [x] Commit data to archives only after user has verified accuracy
- [x] Reset workflow while preserving username

**Comment by nohelix** [comment]
I am getting an error on the graphs of:
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database

**Comment by tofof** [comment]
See `admin tools/font setup.R`

**Comment by nohelix** [comment]
> I am getting an error on the graphs of: Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font family not found in Windows font database

Fixed and run on all work station computers. It required the complete setup ☹️

**Comment by nohelix** [comment]
> Ben wanted .. some other option
> Other alternative for when Rxn vs dB doesn't make sense due to only 1 intensity

Other option was a Hit% graph. For discussion on graphing improvements, see issue #45

**Comment by nohelix** [comment]
Would it be possible to capture the console messages (i.e. the write lines, etc) to a log file?

It seems like sink would allow this.

**Comment by tofof** [comment]
Ready for deployment.
