### ISSUE TITLE
tidyselect warning about 'select'

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#51]
message:
Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.

> Please use `all_of()` or `any_of()` instead.
>   # Was:
>   data %>% select(what_to_graph)
> 
>   # Now:
>   data %>% select(all_of(what_to_graph))
> 
> See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.

Occurs in Graphing.R and probably others but the warning is only generated once every 8 hours. This should occur anywhere I use dplyr::select.

**Comment by tofof** [comment]
fixed by c31cf45
