### ISSUE TITLE
Issue with first attempt to analyze

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#57]
[2023-04-13.log](https://github.com/Auerbach-Lab/Behavior-autoanalysis/files/11223897/2023-04-13.log)
[2023-04-13.txt](https://github.com/Auerbach-Lab/Behavior-autoanalysis/files/11223901/2023-04-13.txt)

**Suspected issue**:
column differences?
Current run_archive columns:
"date"                 "time"                 "box"                  "rat_name"             "rat_ID"               "weight"               "file_name"            "assignment"          "summary"              "stim_type"            "analysis_type"        "stats"                "block_size"           "complete_block_count" "invalid"              "comments"             "warnings_list"        "omit_list"            "UUID"    

When issue occurred:
Happened after hitting analyze. No output other than error to screen.

File: 2023-4-13 LP3

**Notes**:
Changes made to app.R to enable running from non-main folder for soft deploy:
```
sink(paste0(host_folder, paste0(Sys.Date() %>% format("%Y-%m-%d"), ".log")), append=TRUE, split=TRUE)
source(paste0(host_folder, "main.R"))
```
where:
```
projects_folder = "Z:\\Behavior-autoanalysis\\"
host_folder = "Z:\\New Behavior-autoanalysis\\"
```

**Comment by tofof** [comment]
yeah sorry
add the following columns
```
scientist
weightProblem
rxnProblem
```
those are needed to record the new information we're collecting
