### ISSUE TITLE
Main: get rat_ID for run_properties when rat_name is checked in the matlab import

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#58]
It is a useful piece of info to have and deriving it once and canonically would be better. Now needed during file name generation.

Will need to go through code as it is derived several times which leads to the possibility of being out of sync.

**Comment by tofof** [comment]
There should be no way for it to actually get out of synch, since every time it is derived it is through the same call, but yes, it's wasteful to do it repeatedly.

**Comment by tofof** [comment]
Closed by [5310e6e](https://github.com/Auerbach-Lab/Behavior-autoanalysis/commit/5310e6ef5fa0108fb0bdd22cfc6819717cc21568)
