### ISSUE TITLE
Issue: 3 new columns are not handled by Process_File

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#59]
New columns: scientist, weightProblem and rxnProblem

These are not added or handled by Process_File so both 1) **manual entry** using the Process_File and 2) auto-**loading of old excel data** do not work as the column number is different.

**Comment by nohelix** [comment]
[deleted_entries.csv](https://github.com/Auerbach-Lab/Behavior-autoanalysis/files/11326547/deleted_entries.csv)
[test.zip](https://github.com/Auerbach-Lab/Behavior-autoanalysis/files/11326554/test.zip)

**Comment by tofof** [comment]
Process File now accepts those as arguments for manual use, and will use imported information if old_file is true. This means that those three columns are now required to be present in old_excel_archive, so Admin scripts that construct that file need updating.
