### ISSUE TITLE
Remove entry erroring

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#86]
Bug appeared after deduplication for #85.
## Issue
Entry is not deleted because the script exits early with "Error in is_logical(x) : object 'backup_data' not found".

❗ The user intractable popup doesn't happen so crash is happening prior to during [line 45](https://github.com/Auerbach-Lab/Behavior-autoanalysis/blob/a0ad99fdef58fbd91f93c33513a038e01c393623/admin%20tools/remove%20entry.R#L45).

## Expected Behavior
Specified entry is deleted

## Reproduce
Use provided [files](https://uofi.box.com/s/f8dzw2nvhch50unuodjaoskxmi0h1eug)
In `remove entry.R`:
```
bad_rats = c("GP2")
bad_date = "today"
restore = FALSE
```
I have also tried with `bad_date = "20231019"`

## Error message
> source("Z:/Behavior-autoanalysis/admin tools/remove entry.R")
A tibble: 1 × 2
      date rat_name
     <dbl> <chr>   
1 20231020 GP2     
Error in is_logical(x) : object 'backup_data' not found

**Comment by tofof** [comment]
Oh, this is because I removed backup from remove entry. Is it essential to be able to not back up the removed data? It was much simpler to make a common code path where backup data is always saved.

Removed the leftover reference to backup_data.
